// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("certificate")
	ScopeName = "github.com/nginx/agent/v3/internal/collector/certificatereceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
